/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport }    from './rutas/__root'
import { Route as IndexRouteImport }   from './rutas/index'
import { Route as EtlRouteImport }     from './rutas/etl'
import { Route as GraficosRouteImport } from './rutas/graficos'
import { Route as SimilitudRouteImport } from './rutas/similitud'
import { Route as RiesgoRouteImport }        from './rutas/riesgo'
import { Route as OrdenamientoRouteImport } from './rutas/ordenamiento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const EtlRoute = EtlRouteImport.update({
  id: '/etl',
  path: '/etl',
  getParentRoute: () => rootRouteImport,
} as any)

const GraficosRoute = GraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => rootRouteImport,
} as any)

const SimilitudRoute = SimilitudRouteImport.update({
  id: '/similitud',
  path: '/similitud',
  getParentRoute: () => rootRouteImport,
} as any)

const RiesgoRoute = RiesgoRouteImport.update({
  id: '/riesgo',
  path: '/riesgo',
  getParentRoute: () => rootRouteImport,
} as any)

const OrdenamientoRoute = OrdenamientoRouteImport.update({
  id: '/ordenamiento',
  path: '/ordenamiento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/':               typeof IndexRoute
  '/etl':            typeof EtlRoute
  '/graficos':       typeof GraficosRoute
  '/similitud':      typeof SimilitudRoute
  '/riesgo':         typeof RiesgoRoute
  '/ordenamiento':   typeof OrdenamientoRoute
}
export interface FileRoutesByTo {
  '/':               typeof IndexRoute
  '/etl':            typeof EtlRoute
  '/graficos':       typeof GraficosRoute
  '/similitud':      typeof SimilitudRoute
  '/riesgo':         typeof RiesgoRoute
  '/ordenamiento':   typeof OrdenamientoRoute
}
export interface FileRoutesById {
  __root__:          typeof rootRouteImport
  '/':               typeof IndexRoute
  '/etl':            typeof EtlRoute
  '/graficos':       typeof GraficosRoute
  '/similitud':      typeof SimilitudRoute
  '/riesgo':         typeof RiesgoRoute
  '/ordenamiento':   typeof OrdenamientoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/etl' | '/graficos' | '/similitud' | '/riesgo' | '/ordenamiento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/etl' | '/graficos' | '/similitud' | '/riesgo' | '/ordenamiento'
  id: '__root__' | '/' | '/etl' | '/graficos' | '/similitud' | '/riesgo' | '/ordenamiento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute:         typeof IndexRoute
  EtlRoute:           typeof EtlRoute
  GraficosRoute:      typeof GraficosRoute
  SimilitudRoute:     typeof SimilitudRoute
  RiesgoRoute:        typeof RiesgoRoute
  OrdenamientoRoute:  typeof OrdenamientoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etl': {
      id: '/etl'
      path: '/etl'
      fullPath: '/etl'
      preLoaderRoute: typeof EtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graficos': {
      id: '/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof GraficosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/similitud': {
      id: '/similitud'
      path: '/similitud'
      fullPath: '/similitud'
      preLoaderRoute: typeof SimilitudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riesgo': {
      id: '/riesgo'
      path: '/riesgo'
      fullPath: '/riesgo'
      preLoaderRoute: typeof RiesgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenamiento': {
      id: '/ordenamiento'
      path: '/ordenamiento'
      fullPath: '/ordenamiento'
      preLoaderRoute: typeof OrdenamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  EtlRoute,
  GraficosRoute,
  SimilitudRoute,
  RiesgoRoute,
  OrdenamientoRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
